server:
  port: 8081
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: springuser
    password: ThePassword
    hikari:
      maximum-pool-size: 16
      connection-timeout: 3000
      leak-detection-threshold: 2000
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true